name       : sdl1-mixer
version    : 1.2.12
release    : 6
source     :
    - https://www.libsdl.org/projects/SDL_mixer/release/SDL_mixer-1.2.12.tar.gz : 1644308279a975799049e4826af2cfc787cad2abb11aa14562e402521f86992a
license    : Zlib
component  : multimedia.library
summary    : SDL Mixer
description: |
    SDL Mixer
builddeps  :
    - pkgconfig32(flac)
    - pkgconfig32(sdl)
    - pkgconfig32(vorbisfile)
emul32     : yes
optimize   : speed
setup      : |
    %configure \
        --disable-music-flac-shared \
        --disable-music-ogg-shared \
        --disable-static
build      : |
    %make
install    : |
    %make_install
