name       : sdl1-mixer
version    : 1.2.12
release    : 2
source     :
    - https://www.libsdl.org/projects/SDL_mixer/release/SDL_mixer-1.2.12.tar.gz : 1644308279a975799049e4826af2cfc787cad2abb11aa14562e402521f86992a
license    : Zlib
summary    : SDL Mixer
description: |
    SDL Mixer
builddeps  :
    - pkgconfig(sdl)
    - pkgconfig(vorbis)
    - pkgconfig(flac)
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
