name       : sdl1-mixer
version    : 1.2.12
release    : 4
source     :
    - https://www.libsdl.org/projects/SDL_mixer/release/SDL_mixer-1.2.12.tar.gz : 1644308279a975799049e4826af2cfc787cad2abb11aa14562e402521f86992a
license    : Zlib
component  : multimedia.library
summary    : SDL Mixer
description: |
    SDL Mixer
builddeps  :
    - pkgconfig(sdl)
    - pkgconfig32(sdl)
    - pkgconfig(vorbis)
    - pkgconfig32(vorbis)
    - pkgconfig(flac)
    - pkgconfig32(flac)
    - glibc-32bit-devel
    - libgcc-32bit
    - libstdc++-32bit
emul32     : yes
optimize   : speed
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
